/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { createPostSchema, postSchema } from "./C:/Users/LORD/Desktop/fotosnap/apps/backend/src/posts/./schemas/trpc.schema.js";

const appRouter = t.router({
  postsRouter: t.router({
    create: publicProcedure
      .input(createPostSchema)
      .output(postSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    finalAll: publicProcedure
      .output(z.array(postSchema))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
